services:
  app:
    image: xursanov70/question-test:v1.0
    container_name: laravel_app
    volumes:
      - laravel_data:/var/www
    env_file:
      - .env
    networks:
      - laravel_network

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - laravel_data:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  jprq:
    image: alpine:latest
    container_name: jprq_tunnel
    command: >
      sh -c "apk add curl libc6-compat socat &&
             curl -fsSL https://jprq.io/install.sh | sh &&
             /usr/local/bin/jprq --version &&
             /usr/local/bin/jprq auth wDqSutIj03Cq8P2nTjfg2wprWS0CfH23HeyN &&
             socat TCP-LISTEN:8000,fork TCP:web:80 &
             exec /usr/local/bin/jprq http 8000 -s testbot"
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_data: