
services:
  app:
    image: xursanov70/base-test-app:v1.0
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - laravel_network

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  jprq:
    image: alpine:latest
    container_name: jprq_tunnel
    command: >
      sh -c "apk add curl &&
             curl -fsSL https://jprq.io/jprq-linux-amd64 -o /usr/local/bin/jprq &&
             chmod +x /usr/local/bin/jprq &&
             jprq http 8000 --auth-token ${JPRQ_AUTH_TOKEN}"
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge